[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:考虑对等待的任务调用 ConfigureAwait", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpClientExtends.GetRangeContent(System.Net.Http.HttpClient,System.String,System.IO.Stream,System.Int32,System.Int32,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:考虑对等待的任务调用 ConfigureAwait", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpClientExtends.GetStringOrNullAsync(System.Net.Http.HttpClient,System.String,System.Text.Encoding)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:考虑对等待的任务调用 ConfigureAwait", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpClientExtends.HeadContentLength(System.Net.Http.HttpClient,System.String)~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:考虑对等待的任务调用 ConfigureAwait", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpConnetctTimeoutHandler.SendAsync(System.Net.Http.HttpRequestMessage,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Net.Http.HttpResponseMessage}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:考虑对等待的任务调用 ConfigureAwait", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.Program.Main(System.String[])~System.Threading.Tasks.Task")]// This file is used by Code Analysis to maintain SuppressMessage

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2008:不要在未传递 TaskScheduler 的情况下创建任务", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.Program.AsyncConnectionTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2008:不要在未传递 TaskScheduler 的情况下创建任务", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.Program.Main(System.String[])~System.Threading.Tasks.Task")]// attributes that are applied to this project.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:请不要将文本作为本地化参数传递", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.AsyncConnection.ProcessReceive~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:请不要将文本作为本地化参数传递", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.AsyncConnection.ProcessSend~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:请不要将文本作为本地化参数传递", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpConnetctTimeoutHandler.SendAsync(System.Net.Http.HttpRequestMessage,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Net.Http.HttpResponseMessage}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:请不要将文本作为本地化参数传递", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.Program.AsyncConnectionTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:请不要将文本作为本地化参数传递", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.Program.Main(System.String[])~System.Threading.Tasks.Task")]// Project-level suppressions either have no target or are given

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:丢失范围之前释放对象", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpClientExtends.GetRangeContent(System.Net.Http.HttpClient,System.String,System.IO.Stream,System.Int32,System.Int32,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:丢失范围之前释放对象", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpConnetctTimeoutHandler.SendAsync(System.Net.Http.HttpRequestMessage,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Net.Http.HttpResponseMessage}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:丢失范围之前释放对象", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.Program.Main(System.String[])~System.Threading.Tasks.Task")]// a specific target and scoped to a namespace, type, member, etc.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:指定 IFormatProvider", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.Program.Main(System.String[])~System.Threading.Tasks.Task")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:指定 StringComparison", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.Program.Main(System.String[])~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:验证公共方法的参数", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.FileQueue`1.Enqueue(System.Collections.Generic.IEnumerable{`0})~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:验证公共方法的参数", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpClientExtends.GetRangeContent(System.Net.Http.HttpClient,System.String,System.IO.Stream,System.Int32,System.Int32,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:验证公共方法的参数", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpClientExtends.GetStringOrNullAsync(System.Net.Http.HttpClient,System.String,System.Text.Encoding)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:验证公共方法的参数", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpClientExtends.HeadContentLength(System.Net.Http.HttpClient,System.String)~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:验证公共方法的参数", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpConnetctTimeoutHandler.SendAsync(System.Net.Http.HttpRequestMessage,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Net.Http.HttpResponseMessage}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:验证公共方法的参数", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpEventListener.OnEventSourceCreated(System.Diagnostics.Tracing.EventSource)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:验证公共方法的参数", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpEventListener.OnEventWritten(System.Diagnostics.Tracing.EventWrittenEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:指定 IFormatProvider", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.Program.Convert(System.String)~System.UInt32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:不捕获常规异常类型", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpClientExtends.GetRangeContent(System.Net.Http.HttpClient,System.String,System.IO.Stream,System.Int32,System.Int32,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:不捕获常规异常类型", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpClientExtends.GetStringOrNullAsync(System.Net.Http.HttpClient,System.String,System.Text.Encoding)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:不捕获常规异常类型", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpClientExtends.HeadContentLength(System.Net.Http.HttpClient,System.String)~System.Threading.Tasks.ValueTask{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:不捕获常规异常类型", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.Program.Main(System.String[])~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:考虑对等待的任务调用 ConfigureAwait", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpClientExtends.GetRangeContent(System.Net.Http.HttpClient,System.String,System.IO.Stream,System.Nullable{System.Int32},System.Nullable{System.Int32},System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:指定 IFormatProvider", Justification = "<挂起>", Scope = "member", Target = "~M:AsyncNet.HttpClientExtends.GetRangeContent(System.Net.Http.HttpClient,System.String,System.IO.Stream,System.Nullable{System.Int32},System.Nullable{System.Int32},System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Boolean}")]